package config

import "Siberat/entity"

func SeedRoles() {
	roles := []entity.RoleUser{
		{NameRole: "Petugas Penetapan"},
		{NameRole: "Petugas Bidang PSIP"},
		{NameRole: "Pejabat Pengawas"},
		{NameRole: "Petugas Bidang PP"},
		{StsDaftar: 1},
		{StsDaftar: 1},
		{StsDaftar: 1},
		{StsDaftar: 0},
		{StsTambahPotensi: 1},
		{StsTambahPotensi: 1},
		{StsTambahPotensi: 1},
		{StsTambahPotensi: 0},
		{StsInfoPab: 1},
		{StsInfoPab: 1},
		{StsInfoPab: 1},
		{StsInfoPab: 1},
		{StsKirimUlangSKKP: 1},
		{StsKirimUlangSKKP: 1},
		{StsKirimUlangSKKP: 1},
		{StsKirimUlangSKKP: 1},
		{StsCetakNAB: 1},
		{StsCetakNAB: 1},
		{StsCetakNAB: 1},
		{StsCetakNAB: 0},
		{StsCetakUlangNAB: 1},
		{StsCetakUlangNAB: 1},
		{StsCetakUlangNAB: 1},
		{StsCetakUlangNAB: 0},
		{StsInfoSubjekPab: 1},
		{StsInfoSubjekPab: 1},
		{StsInfoSubjekPab: 1},
		{StsInfoSubjekPab: 1},
		{StsDaftarUlangPotBaru: 1},
		{StsDaftarUlangPotBaru: 1},
		{StsDaftarUlangPotBaru: 1},
		{StsDaftarUlangPotBaru: 0},
		{StsUserMngmt: 0},
		{StsUserMngmt: 1},
		{StsUserMngmt: 0},
		{StsUserMngmt: 0},
		{StsNabMngmt: 0},
		{StsNabMngmt: 1},
		{StsNabMngmt: 0},
		{StsNabMngmt: 0},
		{StsInfoNjab: 1},
		{StsInfoNjab: 1},
		{StsInfoNjab: 1},
		{StsInfoNjab: 1},
		{StsInfoUser: 0},
		{StsInfoUser: 1},
		{StsInfoUser: 0},
		{StsInfoUser: 1},
		{StsTable: 1},
		{StsTable: 1},
		{StsTable: 1},
		{StsTable: 1},
		{StsTableMngmt: 1},
		{StsTableMngmt: 1},
		{StsTableMngmt: 1},
		{StsTableMngmt: 0},
		{StsVerif: 1},
		{StsVerif: 1},
		{StsVerif: 1},
		{StsVerif: 0},
	}

	for _, role := range roles {
		DB.FirstOrCreate(&role, entity.RoleUser{NameRole: role.NameRole})
	}
}