package dto

type GetTrnabRequest struct {
	IdTrnab string `json:"id_trnab" gorm:"column:id_trnab" form:"id_trnab"`
}

type GetTrnabResponse struct {
	IdTrnab           string  `json:"id_trnab"`
	KdMohon1          string  `json:"kd_mohon1"`
	KdMohon2          string  `json:"kd_mohon2"`
	KdMohon3          string  `json:"kd_mohon3"`
	KdMohon4          string  `json:"kd_mohon4"`
	KdMohon5          string  `json:"kd_mohon5"`
	KdMohon6          string  `json:"kd_mohon6"`
	KdStatus          string  `json:"kd_status"`
	KdWilProses       string  `json:"kd_wil_proses"`
	TgDaftar          string  `json:"tg_daftar"`
	JamDaftar         string  `json:"jam_daftar"`
	IdUserDaftar      string  `json:"id_user_daftar"`
	NmUserDaftar      string  `json:"nm_user_daftar"`
	TgTetap           string  `json:"tg_tetap"`
	JamTetap          string  `json:"jam_tetap"`
	IdUserTetap       *string `json:"id_user_tetap"`
	NmUserTetap       string  `json:"nm_user_tetap"`
	TgBayar           string  `json:"tg_bayar"`
	JamBayar          string  `json:"jam_bayar"`
	IdUserBayar       *string `json:"id_user_bayar"`
	NmUserBayar       string  `json:"nm_user_bayar"`
	KdChannelBayar    string  `json:"kd_channel_bayar"`
	BeaBbnabPok       string  `json:"bea_bbnab_pok"`
	BeaBbnabDen       string  `json:"bea_bbnab_den"`
	BeaPabPok         string  `json:"bea_pab_pok"`
	BeaPabPok1        string  `json:"bea_pab_pok1"`
	BeaPabPok2        string  `json:"bea_pab_pok2"`
	BeaPabPok3        string  `json:"bea_pab_pok3"`
	BeaPabPok4        string  `json:"bea_pab_pok4"`
	BeaPabPok5        string  `json:"bea_pab_pok5"`
	BeaPabDen         string  `json:"bea_pab_den"`
	BeaPabDen1        string  `json:"bea_pab_den1"`
	BeaPabDen2        string  `json:"bea_pab_den2"`
	BeaPabDen3        string  `json:"bea_pab_den3"`
	BeaPabDen4        string  `json:"bea_pab_den4"`
	BeaPabDen5        string  `json:"bea_pab_den5"`
	BeaBbnabPokD      string  `json:"bea_bbnab_pok_d"`
	BeaBbnabDenD      string  `json:"bea_bbnab_den_d"`
	BeaPabPokD        string  `json:"bea_pab_pok_d"`
	BeaPabPok1D       string  `json:"bea_pab_pok1_d"`
	BeaPabPok2D       string  `json:"bea_pab_pok2_d"`
	BeaPabPok3D       string  `json:"bea_pab_pok3_d"`
	BeaPabPok4D       string  `json:"bea_pab_pok4_d"`
	BeaPabPok5D       string  `json:"bea_pab_pok5_d"`
	BeaPabDenD        string  `json:"bea_pab_den_d"`
	BeaPabDen1D       string  `json:"bea_pab_den1_d"`
	BeaPabDen2D       string  `json:"bea_pab_den2_d"`
	BeaPabDen3D       string  `json:"bea_pab_den3_d"`
	BeaPabDen4D       string  `json:"bea_pab_den4_d"`
	BeaPabDen5D       string  `json:"bea_pab_den5_d"`
	TgAkhirPajak      string  `json:"tg_akhir_pajak"`
	TgAkhirPajakBaru  string  `json:"tg_akhir_pajak_baru"`
	TgAkhirPajakLama  string  `json:"tg_akhir_pajak_lama"`
	TgFaktur          *string `json:"tg_faktur"`
	TgFiskal          *string `json:"tg_fiskal"`
	TgGntmesin        *string `json:"tg_gntmesin"`
	TgKwitansi        *string `json:"tg_kwitansi"`
	TgUben            *string `json:"tg_uben"`
	TgBlockir         *string `json:"tg_blockir"`
	NoAb1             string  `json:"no_ab1"`
	NoAb2             string  `json:"no_ab2"`
	NoAb3             string  `json:"no_ab3"`
	IdObjekPajak      string  `json:"id_objek_pajak"`
	KdMerekAb         string  `json:"kd_merek_ab"`
	NmMerekAb         string  `json:"nm_merek_ab"`
	NmModelAb         string  `json:"nm_model_ab"`
	KdJenisAb         string  `json:"kd_jenis_ab"`
	ThBuatan          string  `json:"th_buatan"`
	NoRangka          string  `json:"no_rangka"`
	NoMesin           string  `json:"no_mesin"`
	WarnaAb           string  `json:"warna_ab"`
	IdBbm             string  `json:"id_bbm"`
	JumlahCc          string  `json:"jumlah_cc"`
	KdWil             string  `json:"kd_wil"`
	KdKepemilikan     string  `json:"kd_kepemilikan"`
	KdBlockir         *string `json:"kd_blockir"`
	TgKepemilikan     string  `json:"tg_kepemilikan"`
	JamKepemilikan    string  `json:"jam_kepemilikan"`
	IdSubjekPajak     string  `json:"id_subjek_pajak"`
	NoKtp             *string `json:"no_ktp"`
	Npwp              *string `json:"npwp"`
	Nib               string  `json:"nib"`
	NmPemilik         string  `json:"nm_pemilik"`
	AlPemilik         string  `json:"al_pemilik"`
	KdWilSubjekPajak  string  `json:"kd_wil_subjek_pajak"`
	KdKelurahan       string  `json:"kd_kelurahan"`
	KdKecamatan       string  `json:"kd_kecamatan"`
	Rt                string  `json:"rt"`
	Rw                string  `json:"rw"`
	IdSubjekPajakType string  `json:"id_subjek_pajak_type"`
	Email             string  `json:"email"`
	NoWa              string  `json:"no_wa"`
	NoHp              string  `json:"no_hp"`
	KdPos             string  `json:"kd_pos"`
	IsAbleBayar       bool    `json:"is_able_bayar"`
	NilaiJual         string  `json:"nilai_jual"`
	Bobot             string  `json:"bobot"`
	BayarKdpn         string  `json:"bayar_kdpn"`
	Ket1              string  `json:"ket1"`
	Ket2              string  `json:"ket2"`
	Ket3              string  `json:"ket3"`
	SelangHari        string  `json:"selang_hari"`
	SelangBulan       string  `json:"selang_bulan"`
	SelangTahun       string  `json:"selang_tahun"`
	UpdatedAt         string  `json:"updated_at"`
	TgKoreksi         *string `json:"tg_koreksi"`
	JamKoreksi        *string `json:"jam_koreksi"`
	IdUserKoreksi     *string `json:"id_user_koreksi"`
	NmUserKoreksi     *string `json:"nm_user_koreksi"`
	NoAb1Lm           *string `json:"no_ab1_lm"`
	NoAb2Lm           *string `json:"no_ab2_lm"`
	NoAb3Lm           *string `json:"no_ab3_lm"`
	KdMerekAbLm       *string `json:"kd_merek_ab_lm"`
	NmMerekAbLm       *string `json:"nm_merek_ab_lm"`
	NmModelAbLm       *string `json:"nm_model_ab_lm"`
	ThBuatanLm        *string `json:"th_buatan_lm"`
	NilaiJualLm       *string `json:"nilai_jual_lm"`
	BobotLm           *string `json:"bobot_lm"`
	KdJenisAbLm       *string `json:"kd_jenis_ab_lm"`
	WarnaAbLm         *string `json:"warna_ab_lm"`
	JumlahCcLm        *string `json:"jumlah_cc_lm"`
	KdKepemilikanLm   *string `json:"kd_kepemilikan_lm"`
	KdBlockirLm       *string `json:"kd_blockir_lm"`
	IsCopied          *string `json:"is_copied"`
	KdCetakTnab       string  `json:"kd_cetak_tnab"`
	TgCetakTnab       *string `json:"tg_cetak_tnab"`
	JamCetakTnab      *string `json:"jam_cetak_tnab"`
	IdUserCetakTnab   *string `json:"id_user_cetak_tnab"`
	NmUserCetakTnab   *string `json:"nm_user_cetak_tnab"`
	KodeBayar         string  `json:"kode_bayar"`
	TagihanPokokTot   string  `json:"tagihan_pokok_tot"`
	TagihanDendaTot   string  `json:"tagihan_denda_tot"`
	KodeBayarExpired  string  `json:"kode_bayar_expired"`
	TagihanNoAb       string  `json:"tagihan_no_ab"`
	TagihanTot        string  `json:"tagihan_tot"`
	UnitKode          string  `json:"unit_kode"`
	IsPabEditable     string  `json:"is_pab_editable"`
}

type HitungUlangRequest struct {
	IDTrnAB           string  `json:"id_trnab"`
	KdMohon1          string  `json:"kd_mohon1"`
	KdMohon2          string  `json:"kd_mohon2"`
	KdMohon3          string  `json:"kd_mohon3"`
	KdMohon4          string  `json:"kd_mohon4"`
	KdMohon5          string  `json:"kd_mohon5"`
	KdMohon6          string  `json:"kd_mohon6"`
	KdStatus          string  `json:"kd_status"`
	KdWilProses       string  `json:"kd_wil_proses"`
	TgDaftar          string  `json:"tg_daftar"`
	JamDaftar         string  `json:"jam_daftar"`
	IdUserDaftar      string  `json:"id_user_daftar"`
	NmUserDaftar      string  `json:"nm_user_daftar"`
	TgTetap           string  `json:"tg_tetap"`
	JamTetap          string  `json:"jam_tetap"`
	IdUserTetap       string  `json:"id_user_tetap"`
	NmUserTetap       string  `json:"nm_user_tetap"`
	TgBayar           *string `json:"tg_bayar"`
	JamBayar          *string `json:"jam_bayar"`
	IdUserBayar       *string `json:"id_user_bayar"`
	NmUserBayar       *string `json:"nm_user_bayar"`
	KdChannelBayar    *string `json:"kd_channel_bayar"`
	BeaBbnabPok       string  `json:"bea_bbnab_pok"`
	BeaBbnabDen       string  `json:"bea_bbnab_den"`
	BeaPabPok         string  `json:"bea_pab_pok"`
	BeaPabPok1        string  `json:"bea_pab_pok1"`
	BeaPabPok2        string  `json:"bea_pab_pok2"`
	BeaPabPok3        string  `json:"bea_pab_pok3"`
	BeaPabPok4        string  `json:"bea_pab_pok4"`
	BeaPabPok5        string  `json:"bea_pab_pok5"`
	BeaPabDen         string  `json:"bea_pab_den"`
	BeaPabDen1        string  `json:"bea_pab_den1"`
	BeaPabDen2        string  `json:"bea_pab_den2"`
	BeaPabDen3        string  `json:"bea_pab_den3"`
	BeaPabDen4        string  `json:"bea_pab_den4"`
	BeaPabDen5        string  `json:"bea_pab_den5"`
	BeaBbnabPokD      string  `json:"bea_bbnab_pok_d"`
	BeaBbnabDenD      string  `json:"bea_bbnab_den_d"`
	BeaPabPokD        string  `json:"bea_pab_pok_d"`
	BeaPabPok1D       string  `json:"bea_pab_pok1_d"`
	BeaPabPok2D       string  `json:"bea_pab_pok2_d"`
	BeaPabPok3D       string  `json:"bea_pab_pok3_d"`
	BeaPabPok4D       string  `json:"bea_pab_pok4_d"`
	BeaPabPok5D       string  `json:"bea_pab_pok5_d"`
	BeaPabDenD        string  `json:"bea_pab_den_d"`
	BeaPabDen1D       string  `json:"bea_pab_den1_d"`
	BeaPabDen2D       string  `json:"bea_pab_den2_d"`
	BeaPabDen3D       string  `json:"bea_pab_den3_d"`
	BeaPabDen4D       string  `json:"bea_pab_den4_d"`
	BeaPabDen5D       string  `json:"bea_pab_den5_d"`
	TgAkhirPajak      string  `json:"tg_akhir_pajak"`
	TgAkhirPajakBaru  string  `json:"tg_akhir_pajak_baru"`
	TgAkhirPajakLama  string  `json:"tg_akhir_pajak_lama"`
	TgFaktur          *string `json:"tg_faktur"`
	TgFiskal          *string `json:"tg_fiskal"`
	TgGntmesin        *string `json:"tg_gntmesin"`
	TgUben            *string `json:"tg_uben"`
	TgBlockir         *string `json:"tg_blockir"`
	NoAb1             string  `json:"no_ab1"`
	NoAb2             string  `json:"no_ab2"`
	NoAb3             string  `json:"no_ab3"`
	IdObjekPajak      string  `json:"id_objek_pajak"`
	KdMerekAb         string  `json:"kd_merek_ab"`
	NmMerekAb         string  `json:"nm_merek_ab"`
	NmModelAb         string  `json:"nm_model_ab"`
	KdJenisAb         *string `json:"kd_jenis_ab"`
	ThBuatan          string  `json:"th_buatan"`
	NoRangka          string  `json:"no_rangka"`
	NoMesin           string  `json:"no_mesin"`
	WarnaAb           string  `json:"warna_ab"`
	IdBbm             string  `json:"id_bbm"`
	JumlahCc          string  `json:"jumlah_cc"`
	KdWil             string  `json:"kd_wil"`
	KdKepemilikan     *string `json:"kd_kepemilikan"`
	KdBlockir         *string `json:"kd_blockir"`
	TgKepemilikan     *string `json:"tg_kepemilikan"`
	JamKepemilikan    *string `json:"jam_kepemilikan"`
	IdSubjekPajak     string  `json:"id_subjek_pajak"`
	NoKtp             string  `json:"no_ktp"`
	Npwp              string  `json:"npwp"`
	Nib               *string `json:"nib"`
	NmPemilik         string  `json:"nm_pemilik"`
	AlPemilik         string  `json:"al_pemilik"`
	KdWilSubjekPajak  string  `json:"kd_wil_subjek_pajak"`
	KdKelurahan       string  `json:"kd_kelurahan"`
	KdKecamatan       string  `json:"kd_kecamatan"`
	Rt                string  `json:"rt"`
	Rw                string  `json:"rw"`
	IdSubjekPajakType *string `json:"id_subjek_pajak_type"`
	Email             *string `json:"email"`
	NoWa              *string `json:"no_wa"`
	NoHp              *string `json:"no_hp"`
	KdPos             *string `json:"kd_pos"`
	IsAbleBayar       *bool   `json:"is_able_bayar"`
	NilaiJual         string  `json:"nilai_jual"`
	Bobot             string  `json:"bobot"`
	BayrKdpn          string  `json:"bayar_kdpn"`
	Ket1              string  `json:"ket1"`
	Ket2              string  `json:"ket2"`
	Ket3              string  `json:"ket3"`
	SelangHari        string  `json:"selang_hari"`
	SelangBulan       string  `json:"selang_bulan"`
	SelangTahun       string  `json:"selang_tahun"`
	UpdatedAt         string  `json:"updated_at"`
	TgKoreksi         *string `json:"tg_koreksi"`
	JamKoreksi        *string `json:"jam_koreksi"`
	IdUserKoreksi     *string `json:"id_user_koreksi"`
	NmUserKoreksi     *string `json:"nm_user_koreksi"`
	NoAb1Lm           *string `json:"no_ab1_lm"`
	NoAb2Lm           *string `json:"no_ab2_lm"`
	NoAb3Lm           *string `json:"no_ab3_lm"`
	KdMerekAbLm       *string `json:"kd_merek_ab_lm"`
	NmMerekAbLm       *string `json:"nm_merek_ab_lm"`
	NmModelAbLm       *string `json:"nm_model_ab_lm"`
	ThBuatanLm        *string `json:"th_buatan_lm"`
	NilaiJualLm       *string `json:"nilai_jual_lm"`
	BobotLm           *string `json:"bobot_lm"`
	KdJenisAbLm       *string `json:"kd_jenis_ab_lm"`
	WarnaAbLm         *string `json:"warna_ab_lm"`
	JumlahCcLm        *string `json:"jumlah_cc_lm"`
	KdKepemilikanLm   *string `json:"kd_kepemilikan_lm"`
	KdBlockirLm       *string `json:"kd_blockir_lm"`
	IsCopied          *string `json:"is_copied"`
}

type HitungUlangResponse struct {
	BeaBBNABPok int64 `json:"bea_bbnab_pok"`
	BeaBBNABDen int64 `json:"bea_bbnab_den"`
	BeaPABPok   int64 `json:"bea_pab_pok"`
	BeaPABDen   int64 `json:"bea_pab_den"`
	BeaPABPok1  int64 `json:"bea_pab_pok1"`
	BeaPABDen1  int64 `json:"bea_pab_den1"`
	BeaPABPok2  int64 `json:"bea_pab_pok2"`
	BeaPABDen2  int64 `json:"bea_pab_den2"`
	BeaPABPok3  int64 `json:"bea_pab_pok3"`
	BeaPABDen3  int64 `json:"bea_pab_den3"`
	BeaPABPok4  int64 `json:"bea_pab_pok4"`
	BeaPABDen4  int64 `json:"bea_pab_den4"`
	BeaPABPok5  int64 `json:"bea_pab_pok5"`
	BeaPABDen5  int64 `json:"bea_pab_den5"`

	BeaBBNABPokD int64 `json:"bea_bbnab_pok_d"`
	BeaBBNABDenD int64 `json:"bea_bbnab_den_d"`
	BeaPABPokD   int64 `json:"bea_pab_pok_d"`
	BeaPABDenD   int64 `json:"bea_pab_den_d"`
	BeaPABPok1D  int64 `json:"bea_pab_pok1_d"`
	BeaPABDen1D  int64 `json:"bea_pab_den1_d"`
	BeaPABPok2D  int64 `json:"bea_pab_pok2_d"`
	BeaPABDen2D  int64 `json:"bea_pab_den2_d"`
	BeaPABPok3D  int64 `json:"bea_pab_pok3_d"`
	BeaPABDen3D  int64 `json:"bea_pab_den3_d"`
	BeaPABPok4D  int64 `json:"bea_pab_pok4_d"`
	BeaPABDen4D  int64 `json:"bea_pab_den4_d"`
	BeaPABPok5D  int64 `json:"bea_pab_pok5_d"`
	BeaPABDen5D  int64 `json:"bea_pab_den5_d"`

	Ket1             string `json:"ket1"`
	Ket2             string `json:"ket2"`
	Ket3             string `json:"ket3"`
	TgAkhirPajak     string `json:"tg_akhir_pajak"`
	TgAkhirPajakBaru string `json:"tg_akhir_pajak_baru"`
	IsAbleBayar      bool   `json:"is_able_bayar"`
	SelangHari       int    `json:"selang_hari"`
	SelangBulan      int    `json:"selang_bulan"`
	SelangTahun      int    `json:"selang_tahun"`
}